
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/Library_db
    username: postgres
    password: pass
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: db/changelog/db-changelog.xml
